version: "3.9"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db